---
title: "Caio Faro"
subtitle: "cfaro@bren.ucsb.edu"
output: 
  html_document: 
    toc: yes
    toc_depth: 4
---

__________
<a href="../" class="btn btn-primary btn-sm">Home</a>
<a href="./" class="btn btn-primary btn-sm">The Team</a>
<a href="../proposal.html" class="btn btn-primary btn-sm">GP Proposal</a>

__________

Caio graduated from *Universidade Gama Filho*, in Rio de Janeiro (Brazil), in 2010 with a Bachelor and Licentiate degrees in Biological Sciences. In 2014 he also graduated from a specialized graduate certification program in Environmental Management.

From 2010 to 2015 he has worked as Field Researcher, Regional Coordinator and State Coordinator for the Rio de Janeiro’s Fisheries Monitoring Program at the *Fisheries Institute Foundation of the State of Rio de Janeiro (FIPERJ)*. Additionally, since 2009 he has been volunteering on-shore with Instituto Sea Shepherd Brasil, the Brazilian office of the NGO Sea Shepherd Conservation Society, mostly with environmental education and marine conservation programs.

Caio is particularly interested in the conservation of sharks, rays and skates. As a Latin American Fisheries Fellow at the Bren School, he is pursuing a specialization in **Coastal Marine Resources Management** and expects to find effective ways to contribute to conservation of ecologically sensitive populations through the adoption of sustainable fisheries practices in Latin America.


[Resume](./caio.pdf)