---
title: "Jael Martinez"
author: "mmartinez@bren.ucsb.edu"
output: 
  html_document: 
    toc: yes
    toc_depth: 4
---

__________
[Home](../index.html) ~ [The Team](../team.html) ~ [GP Proposal](../proposal.html)

__________

Jael Martinez graduated in 2015 from *Universidad San Francisco de Quito-Ecuador* as a biologist with a minor in journalism. During her undergraduate studies she became interested in Galapagos sea lions and she conducted her thesis in hematology to understand the health and human impacts on sea lions in San Cristobal Island. During her bachelor studies she performed an independent study to find out the patterns of consumption of fish species and seafood from a representative sample of Quito, the second biggest city of Ecuador. She also volunteered as an observer in the CETACEA project, where she participated in the research cruise for cetaceans off the coast of Ecuador.

After her undergraduate studies she worked as a research lab technician at the *Laboratory of Aquatic Ecology (LEA-USFQ)* at Universidad San Francisco de Quito. Her work involved helping with research project within several topics such as taxonomy of freshwater insects and bio-monitoring of freshwater and maintenance of ecological flows to help the conservation of rivers and integrated management of water resources in Ecuador.

Jael’s main interest focus on the dynamics of communities living near watershed and marine ecosystem, citizen-based enforcement of environmental laws and how communication can improve environmental conditions.

As a MESM student she is pursuing the **Economics and Politics of the Environment** specialization and she looks forward on gaining experience on public policies dealing with environmental problems and resources.


[Resume](./jael.pdf)