---
title: "Melaina Wright"
subtitle: "mwright@bren.ucsb.edu"
output: 
  html_document: 
    toc: yes
    toc_depth: 4
---

__________
<a href="../" class="btn btn-primary btn-sm">Home</a>
<a href="./" class="btn btn-primary btn-sm">The Team</a>
<a href="../proposal.html" class="btn btn-primary btn-sm">GP Proposal</a>

__________

Melaina Wright graduated in 2015 with Latin honors from *Wellesley College* with a Bachelor of Arts in Biological Sciences and a minor in Environmental Studies. During her undergraduate studies, she worked as a biology and statistics tutor, was president of the Biological Chemistry and Biology Club, and was co-founder of the *Wellesley College Chapter of Science Club for Girls* which aims to increase the self-confidence and literacy of young girls in the STEM sciences. She was also involved in experiments that determined the percent increase in parasitic infection of Daphnia from Lake Baikal, Russia with increases in temperature likely to occur with climate change.

Under the direction of Dr. Koslow at *Scripps Institution of Oceanography*, she used multivariate statistics to determine the sampling requirements for creating a long-term monitoring program for fish communities (publication in press). At the Duke University Marine Lab, she determined if there are genetically distinct populations shortfin mako sharks. She also participated in the UNC-IMS pelagic longline shark survey, which collects data on the change in abundance, size, and species diversity of sharks off the coast of North Carolina. In conjunction with the data from this survey, she synthesized genetic information and population recruitment models to determine whether or not the dusky shark should be listed as threatened under the Endangered Species Act. 

As a MESM student at the Bren School of Environmental Science & Management, Melaina is specializing in **Coastal Marine Resources Management**. Her main interest is in improving the ecological and socioeconomic sustainability of fisheries in the United States. She looks forward to gaining knowledge and experience in coastal and ocean policy, economics, and environmental law with respect to fisheries management during her time at Bren.


[Resume](docs/melaina.pdf)